Update kpr2ksc
grep " 0    0    0" aaa.klist_band | wc -l

diff --git a/kpr2ksc b/kpr2ksc
--- a/kpr2ksc
+++ b/kpr2ksc
@@ -9,7 +9,7 @@ then
   echo "After execution, your klist file will be renamed with *_orig"
   echo "and the modified klist_file will replace your initial file"
   echo
-  exit 0
+  exit 1
 fi
 
 if [ ! -e $1 ]
@@ -18,10 +18,10 @@ then
   echo "I cannot find the specified file:"
   echo "$(pwd)/$1"
   echo
-  echo "You must put the *.klist_band file name correctly"
+  echo "You must put your *.klist_band file name correctly"
   echo "and make sure that the file exists"
   echo
-  exit 0
+  exit 1
 fi
 
 multx=$(echo $2 | awk -F':' '{print $1}')
@@ -34,7 +34,7 @@ then
   echo "You must specify the multiplicity in X:Y:Z format Where X,Y and Z"
   echo "are integers describing multiplicity in that direcition"
   echo
-  exit 0
+  exit 1
 fi
 
 script_dir=`realpath -s $0`
@@ -64,6 +64,26 @@ rm frac_path numer_path denom_path common_path denom_common red_path_all red_pat
 cat num_den_com | awk '{printf("%15d%5d%5d%5d%5.1f\n",$1*$7/$4,$2*$7/$5,$3*$7/$6,$7,2.0)}' > $PRIM_PATH".f2b"
 printf "END" >> ${PRIM_PATH}.f2b
 
+rm num_den_com
+
+if [ $(cat ${PRIM_PATH}.f2b | wc -l) -lt 2 ]
+then
+  echo
+  echo "Something went wrong but I was unable to detect your mistake"
+  echo "Please try to repeat your steps more carefully"
+  echo 
+  exit 2
+fi
+
+if [ grep " 0    0    0" ${PRIM_PATH}.f2b | wc -l -gt 2 ]
+then
+  echo
+  echo "Something went wrong but I was unable to detect your mistake"
+  echo "Please try to repeat your steps more carefully"
+  echo 
+  exit 2
+fi
+
 if [ -e ${PRIM_PATH}_orig ]
 then
   bck=0
@@ -82,7 +102,7 @@ else
 fi
 mv ${PRIM_PATH}.f2b $PRIM_PATH
 
-rm num_den_com
+sed -i'' '1 s/$/    Klist file generated for fold2bloch by k2prksc/' $PRIM_PATH
 
 echo
 echo "############################################################
